// sub-apps/vue-app-1/src/components/Layout/AppHeader.vue
<template>
  <a-layout-header class="app-header">
    <div class="header-content">
      <div class="header-left">
        <h2 class="app-title">Vue消息中心</h2>
      </div>
      
      <div class="header-right">
        <a-space>
          <!-- 通知按钮 -->
          <a-badge :count="unreadCount" :offset="[10, 0]">
            <a-button 
              type="text" 
              shape="circle" 
              @click="$router.push('/notifications')"
            >
              <template #icon>
                <bell-outlined />
              </template>
            </a-button>
          </a-badge>
          
          <!-- 主题切换 -->
          <a-switch 
            v-model:checked="isDarkMode"
            @change="toggleTheme"
            checked-children="🌙"
            un-checked-children="☀️"
          />
          
          <!-- 用户菜单 -->
          <a-dropdown>
            <a-button type="text">
              <template #icon>
                <user-outlined />
              </template>
              Vue用户
              <down-outlined />
            </a-button>
            <template #overlay>
              <a-menu>
                <a-menu-item key="profile">
                  <user-outlined />
                  个人资料
                </a-menu-item>
                <a-menu-item key="settings">
                  <setting-outlined />
                  设置
                </a-menu-item>
                <a-menu-divider />
                <a-menu-item key="logout">
                  <logout-outlined />
                  退出登录
                </a-menu-item>
              </a-menu>
            </template>
          </a-dropdown>
        </a-space>
      </div>
    </div>
  </a-layout-header>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useStore } from 'vuex';
import { 
  BellOutlined, 
  UserOutlined, 
  DownOutlined,
  SettingOutlined,
  LogoutOutlined
} from '@ant-design/icons-vue';

const store = useStore();

// 计算属性
const unreadCount = computed(() => store.state.messages.unreadCount);
const isDarkMode = computed({
  get: () => store.state.settings.theme === 'dark',
  set: (value) => store.dispatch('updateTheme', value ? 'dark' : 'light')
});

// 方法
const toggleTheme = (dark: boolean) => {
  const theme = dark ? 'dark' : 'light';
  store.dispatch('updateTheme', theme);
  
  // 应用主题到文档
  document.documentElement.setAttribute('data-theme', theme);
};
</script>

<style scoped>
.app-header {
  background: #fff;
  border-bottom: 1px solid #f0f0f0;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
  padding: 0;
}

.header-content {
  display: flex;
  justify-content: space-between;
  align-items: center;
  height: 100%;
  padding: 0 24px;
  max-width: 1200px;
  margin: 0 auto;
}

.header-left {
  display: flex;
  align-items: center;
}

.app-title {
  margin: 0;
  color: #1890ff;
  font-weight: 600;
}

.header-right {
  display: flex;
  align-items: center;
}

/* 暗色主题 */
[data-theme="dark"] .app-header {
  background: #001529;
  border-bottom-color: #303030;
}

[data-theme="dark"] .app-title {
  color: #fff;
}
</style>

// apps/sub-apps/react-app-4/src/components/Layout/AppHeader.tsx
import React, { useState } from 'react';
import { Layout, Button, Switch, Dropdown, Avatar, Badge, Space, Tooltip, Typography } from 'antd';
import { 
  MenuFoldOutlined, 
  MenuUnfoldOutlined, 
  BellOutlined, 
  UserOutlined, 
  SettingOutlined,
  LogoutOutlined,
  MoonOutlined,
  SunOutlined
} from '@ant-design/icons';
import { observer } from 'mobx-react-lite';
import { dashboardStore } from '../../store/DashboardStore';
import { globalEventBus } from '@shared/communication/event-bus';
import { EVENT_TYPES } from '@shared/types/events';

const { Header } = Layout;
const { Title } = Typography;

interface AppHeaderProps {
  collapsed?: boolean;
  onCollapse?: (collapsed: boolean) => void;
}

const AppHeader: React.FC<AppHeaderProps> = observer(({ 
  collapsed = false, 
  onCollapse 
}) => {
  const [isDarkMode, setIsDarkMode] = useState(false);

  const handleThemeToggle = (checked: boolean) => {
    setIsDarkMode(checked);
    const theme = checked ? 'dark' : 'light';
    
    // 更新全局主题
    document.documentElement.setAttribute('data-theme', theme);
    
    // 发送主题变更事件
    globalEventBus.emit({
      type: EVENT_TYPES.THEME_CHANGE,
      source: 'react-app-4',
      timestamp: new Date().toISOString(),
      id: `theme-change-${Date.now()}`,
      data: { theme }
    });
  };

  const handleMenuToggle = () => {
    onCollapse?.(!collapsed);
  };

  const userMenuItems = [
    {
      key: 'profile',
      icon: <UserOutlined />,
      label: '个人资料',
    },
    {
      key: 'settings',
      icon: <SettingOutlined />,
      label: '设置',
    },
    {
      type: 'divider' as const,
    },
    {
      key: 'logout',
      icon: <LogoutOutlined />,
      label: '退出登录',
      onClick: () => {
        globalEventBus.emit({
          type: EVENT_TYPES.USER_LOGOUT,
          source: 'react-app-4',
          timestamp: new Date().toISOString(),
          id: `logout-${Date.now()}`,
          data: {}
        });
      }
    },
  ];

  const notificationMenuItems = [
    {
      key: '1',
      label: (
        <div>
          <div style={{ fontWeight: 'bold' }}>系统通知</div>
          <div style={{ fontSize: '12px', color: '#666' }}>数据更新完成</div>
        </div>
      ),
    },
    {
      key: '2',
      label: (
        <div>
          <div style={{ fontWeight: 'bold' }}>性能警告</div>
          <div style={{ fontSize: '12px', color: '#666' }}>内存使用率较高</div>
        </div>
      ),
    },
    {
      type: 'divider' as const,
    },
    {
      key: 'all',
      label: '查看全部通知',
      style: { textAlign: 'center' as const }
    },
  ];

  return (
    <Header 
      className="app-header"
      style={{
        padding: '0 16px',
        background: '#fff',
        borderBottom: '1px solid #f0f0f0',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        position: 'sticky',
        top: 0,
        zIndex: 1000,
        boxShadow: '0 2px 8px rgba(0,0,0,0.06)'
      }}
    >
      {/* 左侧区域 */}
      <div style={{ display: 'flex', alignItems: 'center' }}>
        <Button
          type="text"
          icon={collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
          onClick={handleMenuToggle}
          style={{
            fontSize: '16px',
            width: 64,
            height: 64,
          }}
        />
        
        <div style={{ marginLeft: 16 }}>
          <Title level={4} style={{ margin: 0, color: '#722ed1' }}>
            数据看板系统
          </Title>
        </div>
      </div>

      {/* 右侧区域 */}
      <div style={{ display: 'flex', alignItems: 'center' }}>
        <Space size="middle">
          {/* 主题切换 */}
          <Tooltip title={isDarkMode ? '切换到浅色模式' : '切换到深色模式'}>
            <Switch
              checked={isDarkMode}
              onChange={handleThemeToggle}
              checkedChildren={<MoonOutlined />}
              unCheckedChildren={<SunOutlined />}
            />
          </Tooltip>

          {/* 实时连接状态 */}
          <Tooltip title={dashboardStore.isRealTimeConnected ? '实时连接正常' : '实时连接断开'}>
            <Badge 
              status={dashboardStore.isRealTimeConnected ? 'success' : 'error'} 
              text="实时数据"
            />
          </Tooltip>

          {/* 通知 */}
          <Dropdown
            menu={{ items: notificationMenuItems }}
            placement="bottomRight"
            arrow
          >
            <Button type="text" icon={<BellOutlined />} size="large">
              <Badge count={2} size="small" />
            </Button>
          </Dropdown>

          {/* 用户菜单 */}
          <Dropdown
            menu={{ items: userMenuItems }}
            placement="bottomRight"
            arrow
          >
            <Button type="text" style={{ padding: '4px 8px' }}>
              <Space>
                <Avatar size="small" icon={<UserOutlined />} />
                <span>管理员</span>
              </Space>
            </Button>
          </Dropdown>
        </Space>
      </div>
    </Header>
  );
});

export default AppHeader;
