// sub-apps/vue-app-1/src/components/Layout/AppSidebar.vue
<template>
  <a-layout-sider 
    v-model:collapsed="collapsed" 
    :trigger="null" 
    collapsible
    class="app-sidebar"
    width="240"
  >
    <div class="sidebar-logo">
      <div class="logo-icon">📧</div>
      <div v-if="!collapsed" class="logo-text">
        <div class="logo-title">消息中心</div>
        <div class="logo-subtitle">Vue App</div>
      </div>
    </div>
    
    <a-menu
      v-model:selectedKeys="selectedKeys"
      mode="inline"
      theme="dark"
      :inline-collapsed="collapsed"
      @click="handleMenuClick"
    >
      <a-menu-item key="/">
        <template #icon>
          <message-outlined />
        </template>
        <span>消息列表</span>
      </a-menu-item>
      
      <a-menu-item key="/notifications">
        <template #icon>
          <bell-outlined />
        </template>
        <span>通知中心</span>
      </a-menu-item>
      
      <a-menu-item key="/communication-demo">
        <template #icon>
          <api-outlined />
        </template>
        <span>通信演示</span>
      </a-menu-item>
      
      <a-menu-divider />
      
      <a-sub-menu key="cross-app">
        <template #icon>
          <appstore-outlined />
        </template>
        <template #title>跨应用导航</template>
        
        <a-menu-item key="main-app" @click="navigateToApp('main', '/communication-demo')">
          <template #icon>
            <home-outlined />
          </template>
          主应用演示
        </a-menu-item>
        
        <a-menu-item key="react-app-1" @click="navigateToApp('react-app-1')">
          <template #icon>
            <user-outlined />
          </template>
          用户管理
        </a-menu-item>
        
        <a-menu-item key="react-app-2" @click="navigateToApp('react-app-2')">
          <template #icon>
            <shopping-outlined />
          </template>
          商品管理
        </a-menu-item>
        
        <a-menu-item key="vue-app-2" @click="navigateToApp('vue-app-2')">
          <template #icon>
            <folder-outlined />
          </template>
          文件管理
        </a-menu-item>
      </a-sub-menu>
    </a-menu>
    
    <!-- 折叠按钮 -->
    <div class="sidebar-trigger" @click="toggleCollapsed">
      <menu-unfold-outlined v-if="collapsed" />
      <menu-fold-outlined v-else />
    </div>
  </a-layout-sider>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import {
  MessageOutlined,
  BellOutlined,
  ApiOutlined,
  AppstoreOutlined,
  HomeOutlined,
  UserOutlined,
  ShoppingOutlined,
  FolderOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined
} from '@ant-design/icons-vue';

// 导入跨应用导航
import { globalRouteManager } from '@shared/communication/navigation';

const route = useRoute();
const router = useRouter();

// 响应式数据
const collapsed = ref(false);
const selectedKeys = ref([route.path]);

// 监听路由变化
watch(() => route.path, (newPath) => {
  selectedKeys.value = [newPath];
});

// 方法
const toggleCollapsed = () => {
  collapsed.value = !collapsed.value;
};

const handleMenuClick = ({ key }: { key: string }) => {
  if (key.startsWith('/')) {
    router.push(key);
  }
};

const navigateToApp = (appName: string, path: string = '/') => {
  globalRouteManager.navigateToApp(appName, path, {
    from: 'vue-app-1',
    timestamp: new Date().toISOString(),
    reason: '侧边栏导航'
  });
};
</script>

<style scoped>
.app-sidebar {
  position: relative;
  background: #001529;
}

.sidebar-logo {
  display: flex;
  align-items: center;
  padding: 16px;
  background: rgba(255, 255, 255, 0.1);
  margin-bottom: 1px;
}

.logo-icon {
  font-size: 24px;
  margin-right: 12px;
}

.logo-text {
  color: #fff;
}

.logo-title {
  font-size: 16px;
  font-weight: 600;
  line-height: 1.2;
}

.logo-subtitle {
  font-size: 12px;
  opacity: 0.7;
  line-height: 1.2;
}

.sidebar-trigger {
  position: absolute;
  bottom: 16px;
  left: 50%;
  transform: translateX(-50%);
  width: 32px;
  height: 32px;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(255, 255, 255, 0.1);
  border-radius: 4px;
  cursor: pointer;
  color: #fff;
  transition: all 0.3s;
}

.sidebar-trigger:hover {
  background: rgba(255, 255, 255, 0.2);
}
</style>

// apps/main-app/src/components/Layout/AppSidebar.tsx
/**
 * 应用侧边栏组件
 * 提供导航菜单功能
 */

import React from 'react';
import { Layout, Menu } from 'antd';
import { useNavigate } from 'react-router-dom';
import {
  DashboardOutlined,
  UserOutlined,
  ShoppingOutlined,
  ShoppingCartOutlined,
  BarChartOutlined,
  SettingOutlined,
  MessageOutlined,
  FolderOutlined,
  MonitorOutlined,
  ApiOutlined
} from '@ant-design/icons';
import type { MenuProps } from 'antd';
import { MicroAppConfig } from '@shared/types';
import './AppSidebar.css';

const { Sider } = Layout;

interface AppSidebarProps {
  collapsed: boolean;
  selectedKeys: string[];
  microApps: MicroAppConfig[];
}

/**
 * 应用侧边栏组件
 */
const AppSidebar: React.FC<AppSidebarProps> = ({
  collapsed,
  selectedKeys,
  microApps
}) => {
  const navigate = useNavigate();

  // 菜单项配置
  const menuItems: MenuProps['items'] = [
    {
      key: '/dashboard',
      icon: <DashboardOutlined />,
      label: '仪表盘',
      onClick: () => navigate('/dashboard')
    },
    {
      key: '/communication-demo',
      icon: <ApiOutlined />,
      label: '通信演示',
      onClick: () => navigate('/communication-demo')
    },
    {
      type: 'divider'
    },
    {
      key: 'react-apps',
      icon: <SettingOutlined />,
      label: 'React应用',
      children: [
        {
          key: '/user-management',
          icon: <UserOutlined />,
          label: '用户管理',
          onClick: () => navigate('/user-management')
        },
        {
          key: '/product-management',
          icon: <ShoppingOutlined />,
          label: '商品管理',
          onClick: () => navigate('/product-management')
        },
        {
          key: '/order-management',
          icon: <ShoppingCartOutlined />,
          label: '订单管理',
          onClick: () => navigate('/order-management')
        },
        {
          key: '/data-dashboard',
          icon: <BarChartOutlined />,
          label: '数据看板',
          onClick: () => navigate('/data-dashboard')
        },
        {
          key: '/settings',
          icon: <SettingOutlined />,
          label: '设置中心',
          onClick: () => navigate('/settings')
        }
      ]
    },
    {
      key: 'vue-apps',
      icon: <SettingOutlined />,
      label: 'Vue应用',
      children: [
        {
          key: '/message-center',
          icon: <MessageOutlined />,
          label: '消息中心',
          onClick: () => navigate('/message-center')
        },
        {
          key: '/file-management',
          icon: <FolderOutlined />,
          label: '文件管理',
          onClick: () => navigate('/file-management')
        },
        {
          key: '/system-monitor',
          icon: <MonitorOutlined />,
          label: '系统监控',
          onClick: () => navigate('/system-monitor')
        }
      ]
    }
  ];

  // 获取默认展开的菜单项
  const getDefaultOpenKeys = (): string[] => {
    const currentPath = selectedKeys[0];
    if (!currentPath) return [];

    if (currentPath.startsWith('/user-management') || 
        currentPath.startsWith('/product-management') ||
        currentPath.startsWith('/order-management') ||
        currentPath.startsWith('/data-dashboard') ||
        currentPath.startsWith('/settings')) {
      return ['react-apps'];
    }

    if (currentPath.startsWith('/message-center') ||
        currentPath.startsWith('/file-management') ||
        currentPath.startsWith('/system-monitor')) {
      return ['vue-apps'];
    }

    return [];
  };

  return (
    <Sider
      trigger={null}
      collapsible
      collapsed={collapsed}
      className="app-sidebar"
      width={240}
      collapsedWidth={64}
    >
      <div className="sidebar-logo">
        <div className="logo-icon">Q</div>
        {!collapsed && (
          <div className="logo-text">
            <div className="logo-title">Qiankun</div>
            <div className="logo-subtitle">微前端</div>
          </div>
        )}
      </div>

      <Menu
        theme="dark"
        mode="inline"
        selectedKeys={selectedKeys}
        defaultOpenKeys={getDefaultOpenKeys()}
        items={menuItems}
        className="sidebar-menu"
      />

      {/* 应用状态指示器 */}
      {!collapsed && (
        <div className="app-status">
          <div className="status-title">应用状态</div>
          <div className="status-list">
            {microApps.map(app => (
              <div key={app.name} className="status-item">
                <div className="status-dot status-online" />
                <span className="status-name">{app.name}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </Sider>
  );
};

export default AppSidebar;
